<?php
/**
 * Generate a string of random characters
 *
 * @param array $args   The arguments to use for this function
 * @return string|null  The random string generated by this function (only 'if($args['echo'] === false)')
 */
function my_random_string($args = array()){
	$my_international_mailbox_options = get_option( 'my_international_mailbox_option_name' ); // Array of All Options
	$country_3 = $my_international_mailbox_options['country_3']; // Country
    
    $defaults = array(  // Set some defaults for the function to use
        'characters'    => '0123456789',
        'length'        => 6,
        'before'        => ''.$country_3.'-',
        'after'         => '',
        'echo'          => false
    );
    $args = wp_parse_args($args, $defaults);    // Parse the args passed by the user with the defualts to generate a final '$args' array
    
    if(absint($args['length']) < 1) // Ensure that the length is valid
        return;
    
    $characters_count = strlen($args['characters']);    // Check how many characters the random string is to be assembled from
    for($i = 0; $i <= $args['length']; $i++) :          // Generate a random character for each of '$args['length']'
    
        $start = mt_rand(0, $characters_count);
        $random_string.= substr($args['characters'], $start, 1);
        
    endfor;
    
    $random_string = $args['before'] . $random_string . $args['after']; // Add the before and after strings to the random string
    
    if($args['echo']) : // Check if the random string shoule be output or returned
        echo $random_string;
    else :
        return $random_string;
    endif;
    
}
